### ISSUE TITLE
Synonym support 

### ISSUE THREAD

**Issue by ChillFish8** [lnx-search/lnx#12]
At the moment theirs a distinct lack of synonym support and generally im not sure how to go about implementing this short of some wildly inefficient system.

**Comment by ChillFish8** [comment]
Closing because this is now implemented!

**Comment by ptming** [comment]
@ChillFish8 i tried to get this working but I've been running into issues. What is the syntax for adding a synonym that matches a phrase? For example if I wanted to have "ny" match against "New York" but setting my synonyms via `["ny:new york"]` does not seem to work. I can see they were accepted by doing a get request against `/indexes/indexname/synonyms` but my query behaves as it did before

**Comment by ptming** [comment]
@ChillFish8 if you can provide some guidance on this endpoint i'd be very appreciative.

**Comment by ptming** [comment]
@ChillFish8 can you provide some guidance on how these work?

**Comment by ChillFish8** [comment]
Hey sorry for the delay @ptming what query are you running? This is probably my bad for not documenting, but currently, this only applies to _fuzzy_ queries. I should fix this in the future.

**Comment by ptming** [comment]
@ChillFish8 

Here is how I tested

### Added Synonyms
`curl -X POST -H "Content-Type: application/json" --data '["ny:new york", "lotr:lord of the rings"]' http://127.0.0.1:8000/indexes/testindex/synonyms`

### Confirmed that the synonyms were added
`curl -X GET -H "Content-Type: application/json"  http://127.0.0.1:8000/indexes/testindex/synonyms`
returns
`{"status":200,"data":{"ny":["new york"],"lotr":["lord of the rings"]}}`

### test queries using text from synonyms
`curl -X POST -H "Content-Type: application/json" --data '{"query":"escape from ny","mode":"fuzzy"}' http://127.0.0.1:8000/indexes/testindex/search`
and
`curl -X POST -H "Content-Type: application/json" --data '{"query":"lotr","mode":"fuzzy"}' http://127.0.0.1:8000/indexes/testindex/search`
I would expect that these should return the same documents that
```
curl -X POST -H "Content-Type: application/json" --data '{"query":"escape from new york","mode":"fuzzy"}' http://127.0.0.1:8000/indexes/testindex/search

curl -X POST -H "Content-Type: application/json" --data '{"query":"lord of the rings","mode":"fuzzy"}' http://127.0.0.1:8000/indexes/testindex/search
```
do but they don't

**Comment by ptming** [comment]
@ChillFish8 any ideas on this?

**Comment by ptming** [comment]
@ChillFish8 does this feature work?

**Comment by ChillFish8** [comment]
I am not sure it works how you expect, but I cannot look into it ATM, I'd recommend ignoring this endpoint for now.
