### ISSUE TITLE
Issues with retaining index data between restarts

### ISSUE THREAD

**Issue by ptming** [lnx-search/lnx#146]
I've been trying out lnx and it's great. However I noticed my index documents are not retained between restarts. I can see that the index configuration itself is restored on restart but the index contains no documents. I noticed that the tantivy files all seem to be getting written to a tmp directory that looks like `/var/folders/r6/y3v948hd5xqcv_b8f_z38xm40000gn/T/.tmpZPbQT1/` which gets wiped when I shut the server down.

Is there a configuration change or command line option that I need to pass to change this behavior so my documents get retained?

**Comment by ChillFish8** [comment]
What is your index config? Are you sure you are not using a temporary index?

**Comment by ptming** [comment]
@ChillFish8 I did not see anything in the documentation site about how to configure that, you can provide an example syntax?
I ran it via `cargo run` as well as using docker.

**Comment by ptming** [comment]
@ChillFish8 can you assist? I'm just using the default `cargo run` and ingesting the demo data from the cli tool

**Comment by ChillFish8** [comment]
Hi @ptming Sorry for the delay, the demo tool uses a pre-configured index which uses a temporary directory because it is designed to be spun up and down without worry. I would recommend manually creating an index with configurations specific to your use case. https://docs.lnx.rs/#tag/Managing-indexes

**Comment by ptming** [comment]
@ChillFish8 oooooh thank you, i see the storage_type values. Please disregard and thank you for your guidance
