### ISSUE TITLE
Delete Endpoint always fails

### ISSUE THREAD

**Issue by miyachan** [lnx-search/lnx#24]
LNX Version: 8d38d386de3ecdb1bced4f55032673860feaccf4

This is an issue that happened between e980494...8d38d386de3ecdb

```sh
$ cat a.json
{
  "name": "my-index",
  "writer_buffer": 6000000,
  "writer_threads": 1,
  "reader_threads": 1,
  "max_concurrency": 10,
  "search_fields": [
    "title"
  ],
  "storage_type": "memory",
  "use_fast_fuzzy": false,
  "strip_stop_words": false,
   "set_conjunction_by_default": false,
  "fields": {
    "title": {
      "type": "text",
      "stored": true
    },
    "description": {
      "type": "text",
      "stored": true
    },
    "id": {
      "type": "u64",
      "indexed": true,
      "stored": true,
      "fast": "single"
    },
 "ts": {
            "type": "date",
            "stored": true,
            "indexed": true,
            "fast": "single"
        }
  },
  "boost_fields": {}
}
$ curl -X POST -d@a.json -H "Content-Type: application/json" http://127.0.0.1:4040/indexes
{"data":"index created","status":200}
$ cat d.json
{
    "id": {"type": "u64", "value": [4]}
}
$ curl -X DELETE -d@d.json -H "Content-Type: application/json" http://localhost:4040/indexes/my-index/documents?wait=true
{"data":"invalid JSON body: Failed to parse the request body as JSON","status":400}
```

### Logs:
```
Aug 30 19:01:42 torako lnx[866518]: [2021-08-30][19:01:42] | tantivy::indexer::segment_updater | INFO  - Running garbage collection
Aug 30 19:01:42 torako lnx[866518]: [2021-08-30][19:01:42] | tantivy::directory::managed_directory | INFO  - Garbage collect
Aug 30 19:01:42 torako lnx[866518]: [2021-08-30][19:01:42] | engine::index::writer | INFO  - [ WRITER @ my-index ][ TRANSACTION 4 ] completed operation COMMIT
Aug 30 19:01:49 torako lnx[866518]: [2021-08-30][19:01:49] | engine::index::reader | INFO  - [ SEARCH @ my-index ] took 120.259µs with limit=20, mode=Normal and 1 results total
Aug 30 19:07:26 torako lnx[866518]: [2021-08-30][19:07:26] | lnx::routes | WARN  - rejecting request due to invalid body: InvalidJsonBody(Error { inner: Error("invalid type: map, expected a string or u32", line: 1, column: 13) })
Aug 30 19:07:51 torako lnx[866518]: [2021-08-30][19:07:51] | lnx::routes | WARN  - rejecting request due to invalid body: InvalidJsonBody(Error { inner: Error("invalid type: map, expected a string or u32", line: 1, column: 13) })
```

**Comment by ChillFish8** [comment]
This was part of the breaking changes mentioned on `0.5.0` this is because the deletion endpoint got the same QOL update as the insertions e.g. no longer needing to explicitly declare the type.

**Comment by ChillFish8** [comment]
This my fault though for forgetting to push the updates to the book.

**Comment by miyachan** [comment]
Ok I think a side-effect of this change is that you can no longer do bulk deletes?

**Comment by ChillFish8** [comment]
Bulk deletes still work in the sense that they will delete anything matching the term. But in terms of multi-value deletes, this wasn't the case to begin which is why I chose to move to the more explicit setup. As mentioned in https://github.com/lnx-search/lnx/releases/tag/0.5.0

**Comment by miyachan** [comment]
Ah I see, does tanvity support bulk deletes? Reason being there isn't a way to update documents.

**Comment by ChillFish8** [comment]
> 
> 
> Ah I see, does tanvity support bulk deletes? Reason being there isn't a way to update documents.

Sort of yes and no (as far as I can tell) It bulk deletes in the sense that any with the term gets removed, but not in the sense that you can just give it a list of terms. So the effective solution would be to loop over each term which I don't know if it's better to do explicitly from a developer perspective. 

On thing I am considering doing is a helper function that allows you to give it a query to delete values but this would still require first searching *then* looping over the resulting docs. So not sure what the best plan of action is.
