### ISSUE TITLE
Mounting volume overwrites binary

### ISSUE THREAD

**Issue by FridgeSeal** [lnx-search/lnx#47]
Hiya!

I’m attempting to run LNX on Kubernetes as a stateful set, but running into an issue - the docs/example code suggests mounting a volume to `etc/lnx` but doing this in Kubernetes causes the contents of that path to be replaced with the attached volume, which means the binary can’t be found.

Is there a way to parametise the storage path so that it doesn’t collide with binary path? 🙂

**Comment by ChillFish8** [comment]
Hello! 

You used to be able to do this however, it caused a bit of a concern with how many places would then have to reference this value outside of it being a global.

What you should be able to do is mount a volume to `etc/lnx/index` as lnx will always mount the index to a folder `index` relative to it.

**Comment by FridgeSeal** [comment]
Excellent, thank you - I will give this a go first thing tomorrow!

**Comment by ChillFish8** [comment]
@FridgeSeal any update on if this worked for you or not? Thanks!

**Comment by FridgeSeal** [comment]
Totally forgot to get back to you! Can confirm, mounting to `/etc/lnx/index` worked perfectly!
Thank you for your help!
